version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'github-actions'
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: 'testdata'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm-testdata'
    open-pull-requests-limit: 10