name: 'Run Prettier with reviewdog'
description: '🐶 Run Prettier with reviewdog to improve code checking, formatting and review experience for your codebase.'
author: 'EPMatt'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
    required: false
  workdir:
    description: |
      Working directory relative to the root directory.
      This is where the action will look for a
      package.json which declares Prettier as a dependency.
      Please note that this is different from the directory
      Prettier will run on, which is defined in the prettier_flags input.
      Default is `.`.
    default: '.'
    required: false
  ### Flags for reviewdog ###
  level:
    description: |
      Report level for reviewdog [info,warning,error].
      Default is `error`.
    default: 'error'
    required: false
  reporter:
    description: |
      Reporter of reviewdog command [github-check,github-pr-check,github-pr-review].
      Default is `github-pr-check`.
    default: 'github-pr-check'
    required: false
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is `added`.
    default: 'added'
    required: false
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false].
      Default is `false`.
    default: 'false'
    required: false
  reviewdog_flags:
    description: |
      Additional reviewdog flags.
      Default is ``.
    default: ''
    required: false
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'prettier'
    required: false
  ### Flags for prettier ###
  prettier_flags:
    description: |
      Flags and args to pass to Prettier.
      If you override this input, please make sure to append to it the directory
      which Prettier will run on.
      The path provided here is relative to the workdir path, provided in the workdir input.
      Default is `.`, which makes Prettier run on the path provided in the workdir input.
    default: '.'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.14.2
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_PRETTIER_FLAGS: ${{ inputs.prettier_flags }}
    - if: ${{ inputs.reporter == 'github-pr-review' && always() }}
      uses: reviewdog/action-suggester@v1
      with:
        github_token: ${{ inputs.github_token }}
        tool_name: ${{ inputs.tool_name }}
        level: ${{ inputs.level }}
        filter_mode: ${{ inputs.filter_mode }}
        fail_on_error: ${{ inputs.fail_on_error }}
        reviewdog_flags: ${{ inputs.reviewdog_flags }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'align-left'
  color: 'blue'
